person = raw_input("Enter a person: ")
place1 = raw_input("Enter a place: ")
adj1 = raw_input("Enter an adjective: ")
plural1 = raw_input("Enter a plural noun: ")
adj2 = raw_input("Enter an adjective: ")
plural2 = raw_input("Enter a plural noun: ")
place2 = raw_input("Enter a place: ")
verb = raw_input("Enter an action verb: ")
plural3 = raw_input("Enter a plural noun: ")
plural4 = raw_input("Enter a plural noun: ")
noun = raw_input("Enter a noun: ")
verb2 = raw_input("Enter an action verb: ")
verb3 = raw_input("Enter an action verb: ")
adj3 = raw_input("Enter an adjective: ")

print "Last summer, my mom and dad too me and %s on a trip to %s."%(person, place1)
print "The weather there is very %s!"%(adj1)
print "Northern %s has many %s, and they make %s %s there."%(place1,plural1,adj2,plural2)
print "Many people also go to %s to %s or see the %s"%(place2,verb,plural3)
print "The people that live there love to eat %s and are very proud of their big %s"%(plural4,noun)
print "They also like to %s in the sun and swim in the %s!"%(verb2,verb3)
print "It was a really %s trip!"%(adj3)
